source "https://rubygems.org"

gem "autoprefixer-rails"
gem "html-proofer"
gem "image_optim"
gem "jekyll", "~> 3.8"
gem "jekyll-assets", "~> 3.0"
gem "jekyll-paginate", "~> 1.1"
gem "jekyll-sitemap", "~> 1.4"
gem "jemoji", "~> 0.12"
gem "mini_magick"
gem "sprockets", "~> 3.7"
gem "uglifier"
gem "nokogiri", "~> 1.8"
gem "kramdown-parser-gfm"